import type { Item, Task } from "@/types/db";
import type { UserProfile } from "@/lib/user-profile";
import { getLevelFromXp } from "@/lib/utils";
import type { TaskCompletionCheckIn } from "@/lib/task-checkin";

export type DailyLog = {
  date: string;
  summary: {
    totalTasks: number;
    totalXP: number;
    totalCrystals: number;
    raceBonusTriggered: string[];
    levelUp: boolean;
    newSkillsUnlocked: string[];
    equipmentAcquired: Item[];
  };
  adventures: AdventureRecord[];
  checkIns: {
    taskId: string;
    type: "text" | "image" | "voice";
    content: string;
    timestamp: number;
  }[];
  journal: {
    autoGenerated: string;
    manualNote?: string;
    mood: "productive" | "tired" | "excited" | "peaceful";
  };
  snapshot: {
    level: number;
    stats: { str: number; int: number; agi: number; cha: number; con: number };
    equipment: {
      weapon?: string;
      armor?: string;
      accessory?: string;
    };
  };
};

export type AdventureRecord = {
  taskId: string;
  taskName: string;
  profession: string;
  difficulty: "easy" | "medium" | "hard";
  monsterName: string;
  location: string;
  duration: number;
  result: "victory" | "retreat";
  rewards: { xp: number; crystals: number; drops: string[] };
  highlights: string[];
};

type MonthlySummary = {
  month: string;
  totalTasks: number;
  totalXP: number;
  totalCrystals: number;
  days: number;
};

export type MilestoneItem = {
  id: string;
  date: string;
  title: string;
  kind: "system" | "manual";
};

export type SnapshotCompareResult = {
  levelDiff: number;
  xpGrowth: number;
  statGrowth: { str: number; int: number; agi: number; cha: number; con: number };
  taskEfficiency: number;
  newHabitsFormed: string[];
};

const DB_NAME = "LifeRPG_Journal";
const DB_VERSION = 3;
const DAILY_STORE = "dailyLogs";
const MONTHLY_STORE = "monthlySummaries";
const SEALS_STORE = "seals";
const MIGRATION_KEY = "life-rpg-daily-logs";

const ITEM_CATALOG: Record<string, Item> = {
  iron_sword: {
    id: "iron_sword",
    name: "铁剑",
    type: "weapon",
    rarity: "common",
    effects: { str: 2 },
    description: "朴素但可靠的近战武器。"
  },
  apprentice_wand: {
    id: "apprentice_wand",
    name: "学徒法杖",
    type: "weapon",
    rarity: "common",
    effects: { int: 2 },
    description: "初学者常备法杖。"
  },
  wind_boots: {
    id: "wind_boots",
    name: "风行靴",
    type: "armor",
    rarity: "rare",
    effects: { agi: 2 },
    description: "让步伐更轻盈。"
  },
  focus_charm: {
    id: "focus_charm",
    name: "专注护符",
    type: "accessory",
    rarity: "rare",
    effects: { xpBonus: 0.05 },
    description: "稳定心神，提高任务效率。"
  }
};

function ymd(iso: string): string {
  return iso.slice(0, 10);
}

function monthOf(date: string): string {
  return date.slice(0, 7);
}

function openJournalDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(DAILY_STORE)) {
        const store = db.createObjectStore(DAILY_STORE, { keyPath: "date" });
        store.createIndex("date", "date", { unique: true });
      }
      if (!db.objectStoreNames.contains(MONTHLY_STORE)) {
        db.createObjectStore(MONTHLY_STORE, { keyPath: "month" });
      }
      if (!db.objectStoreNames.contains(SEALS_STORE)) {
        db.createObjectStore(SEALS_STORE, { keyPath: "date" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function withStore<T>(
  storeName: string,
  mode: IDBTransactionMode,
  run: (store: IDBObjectStore) => Promise<T> | T
): Promise<T> {
  const db = await openJournalDb();
  return new Promise<T>((resolve, reject) => {
    const tx = db.transaction(storeName, mode);
    const store = tx.objectStore(storeName);
    let out!: T;
    tx.onerror = () => reject(tx.error);
    tx.onabort = () => reject(tx.error);
    tx.oncomplete = () => resolve(out);
    Promise.resolve(run(store))
      .then((val) => {
        out = val;
      })
      .catch(reject);
  });
}

function reqToPromise<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

export async function listDailyLogs(): Promise<DailyLog[]> {
  await migrateLegacyLocalStorageIfNeeded();
  return withStore(DAILY_STORE, "readonly", async (store) => {
    const rows = await reqToPromise(store.getAll() as IDBRequest<DailyLog[]>);
    return rows.sort((a, b) => (a.date > b.date ? -1 : 1));
  });
}

async function getDailyLogByDate(date: string): Promise<DailyLog | undefined> {
  return withStore(DAILY_STORE, "readonly", async (store) => {
    const row = await reqToPromise(store.get(date) as IDBRequest<DailyLog | undefined>);
    return row;
  });
}

async function putDailyLog(log: DailyLog): Promise<void> {
  await withStore(DAILY_STORE, "readwrite", async (store) => {
    store.put(log);
  });
}

async function deleteDailyLog(date: string): Promise<void> {
  await withStore(DAILY_STORE, "readwrite", async (store) => {
    store.delete(date);
  });
}

async function getMonthlySummary(month: string): Promise<MonthlySummary | undefined> {
  return withStore(MONTHLY_STORE, "readonly", async (store) => {
    const row = await reqToPromise(store.get(month) as IDBRequest<MonthlySummary | undefined>);
    return row;
  });
}

async function putMonthlySummary(summary: MonthlySummary): Promise<void> {
  await withStore(MONTHLY_STORE, "readwrite", async (store) => {
    store.put(summary);
  });
}

export async function listMonthlySummaries(): Promise<MonthlySummary[]> {
  await migrateLegacyLocalStorageIfNeeded();
  return withStore(MONTHLY_STORE, "readonly", async (store) => {
    const rows = await reqToPromise(store.getAll() as IDBRequest<MonthlySummary[]>);
    return rows.sort((a, b) => (a.month > b.month ? -1 : 1));
  });
}

async function migrateLegacyLocalStorageIfNeeded(): Promise<void> {
  const raw = localStorage.getItem(MIGRATION_KEY);
  if (!raw) return;
  try {
    const old = JSON.parse(raw) as DailyLog[];
    for (const item of old) {
      await putDailyLog(item);
    }
    localStorage.removeItem(MIGRATION_KEY);
  } catch {
    // ignore bad legacy payload
  }
}

function inferMood(summary: DailyLog["summary"]): DailyLog["journal"]["mood"] {
  if (summary.levelUp || summary.totalXP >= 260) return "excited";
  if (summary.totalTasks >= 4) return "productive";
  if (summary.totalTasks <= 1 && summary.totalXP < 40) return "tired";
  return "peaceful";
}

function calculatePower(stats: DailyLog["snapshot"]["stats"]): number {
  return Math.round(stats.str * 1.2 + stats.int * 1.2 + stats.agi + stats.cha + stats.con * 1.3);
}

export function generateDailyJournal(log: DailyLog): string {
  const parts: string[] = [];
  parts.push(`📅 ${log.date} 冒险日志\n`);
  parts.push(`今日等级：Lv.${log.snapshot.level} | 战力评估：${calculatePower(log.snapshot.stats)}\n`);

  if (log.summary.totalTasks === 0) {
    parts.push("今日在城镇休息，为明日养精蓄锐。\n");
  } else {
    parts.push(
      `今日出征${log.summary.totalTasks}次，斩获${log.summary.totalXP}XP，${log.summary.totalCrystals}晶石。\n`
    );
  }

  if (log.summary.levelUp) {
    parts.push("🎉 恭喜升级！今日实力获得质的飞跃！\n");
  }

  const topAdventures = log.adventures
    .filter((a) => a.result === "victory")
    .sort((a, b) => b.rewards.xp - a.rewards.xp)
    .slice(0, 3);

  if (topAdventures.length > 0) {
    parts.push("\n⚔️ 精彩战役：\n");
    topAdventures.forEach((adv, i) => {
      parts.push(
        `${i + 1}. 在${adv.location}遭遇${adv.monsterName}，${adv.highlights.join("，")}，${adv.duration}分钟苦战后取得胜利，获得${
          adv.rewards.drops.join("、") || "战利品若干"
        }。\n`
      );
    });
  }

  if (log.checkIns.length > 0) {
    parts.push(`\n📸 今日留下了${log.checkIns.length}个高光时刻。\n`);
    log.checkIns.slice(0, 6).forEach((ci, i) => {
      if (ci.type === "text") parts.push(`  时刻${i + 1}：${ci.content.substring(0, 30)}...\n`);
      else if (ci.type === "image") parts.push(`  时刻${i + 1}：[图片记录]\n`);
      else parts.push(`  时刻${i + 1}：[语音记录]\n`);
    });
  }

  parts.push("\n💪 属性变化：");
  parts.push(
    `力量${log.snapshot.stats.str} | 智力${log.snapshot.stats.int} | 敏捷${log.snapshot.stats.agi} | 魅力${log.snapshot.stats.cha} | 体质${log.snapshot.stats.con}`
  );
  return parts.join("");
}

function difficultyToRecord(d: Task["difficulty"]): AdventureRecord["difficulty"] {
  if (d === "Hard") return "hard";
  if (d === "Normal") return "medium";
  return "easy";
}

export async function appendDailyAdventureLog(input: {
  completedAt: string;
  task: Task;
  actualDuration: number;
  finalXp: number;
  finalCrystals: number;
  raceBonusTags: string[];
  levelUp: boolean;
  unlockedSkills: string[];
  droppedEquipmentIds: string[];
  adventureMeta: {
    monsterName?: string;
    location?: string;
    highlights: string[];
    result: "victory" | "retreat";
    drops: string[];
  };
  profileAfterCompletion: UserProfile | null;
  profileXpAfterCompletion: number;
}): Promise<void> {
  const date = ymd(input.completedAt);
  const existing = await getDailyLogByDate(date);
  const base: DailyLog =
    existing
      ? existing
      : {
          date,
          summary: {
            totalTasks: 0,
            totalXP: 0,
            totalCrystals: 0,
            raceBonusTriggered: [],
            levelUp: false,
            newSkillsUnlocked: [],
            equipmentAcquired: []
          },
          adventures: [],
          checkIns: [],
          journal: {
            autoGenerated: "",
            mood: "peaceful"
          },
          snapshot: {
            level: 1,
            stats: { str: 0, int: 0, agi: 0, cha: 0, con: 0 },
            equipment: {}
          }
        };

  base.adventures.push({
    taskId: input.task.id,
    taskName: input.task.title,
    profession: input.task.profession,
    difficulty: difficultyToRecord(input.task.difficulty),
    monsterName: input.adventureMeta.monsterName ?? "未知魔物",
    location: input.adventureMeta.location ?? "未知区域",
    duration: input.actualDuration,
    result: input.adventureMeta.result,
    rewards: {
      xp: input.finalXp,
      crystals: input.finalCrystals,
      drops: input.adventureMeta.drops
    },
    highlights: input.adventureMeta.highlights
  });

  base.summary.totalTasks += 1;
  base.summary.totalXP += input.finalXp;
  base.summary.totalCrystals += input.finalCrystals;
  base.summary.levelUp = base.summary.levelUp || input.levelUp;
  for (const tag of input.raceBonusTags) {
    if (!base.summary.raceBonusTriggered.includes(tag)) base.summary.raceBonusTriggered.push(tag);
  }
  for (const node of input.unlockedSkills) {
    if (!base.summary.newSkillsUnlocked.includes(node)) base.summary.newSkillsUnlocked.push(node);
  }
  for (const id of input.droppedEquipmentIds) {
    const item = ITEM_CATALOG[id];
    if (item && !base.summary.equipmentAcquired.some((it) => it.id === item.id)) {
      base.summary.equipmentAcquired.push(item);
    }
  }

  const vc = input.profileAfterCompletion?.virtualCharacter;
  base.snapshot = {
    level: getLevelFromXp(input.profileXpAfterCompletion),
    stats: {
      str: vc?.str ?? 0,
      int: vc?.int ?? 0,
      agi: vc?.agi ?? 0,
      cha: vc?.cha ?? 0,
      con: vc?.con ?? 0
    },
    equipment: {
      weapon: vc?.equipment.weapon?.name,
      armor: vc?.equipment.armor?.name,
      accessory: vc?.equipment.accessory?.name
    }
  };
  base.journal.mood = inferMood(base.summary);
  base.journal.autoGenerated = generateDailyJournal(base);
  await putDailyLog(base);
}

export async function appendDailyCheckIn(input: {
  completedAt: string;
  taskId: string;
  checkIn?: TaskCompletionCheckIn;
}): Promise<void> {
  if (!input.checkIn) return;
  const date = ymd(input.completedAt);
  const next = await getDailyLogByDate(date);
  if (!next) return;
  const ts = Date.now();
  if (input.checkIn.text?.trim()) {
    next.checkIns.push({
      taskId: input.taskId,
      type: "text",
      content: input.checkIn.text.trim(),
      timestamp: ts
    });
  }
  for (const image of input.checkIn.images ?? []) {
    next.checkIns.push({
      taskId: input.taskId,
      type: "image",
      content: image,
      timestamp: ts
    });
  }
  if (input.checkIn.voice) {
    next.checkIns.push({
      taskId: input.taskId,
      type: "voice",
      content: input.checkIn.voice,
      timestamp: ts
    });
  }
  await putDailyLog(next);
}

export async function sealDailyJournal(date: string): Promise<DailyLog | null> {
  const log = await getDailyLogByDate(date);
  if (!log || log.summary.totalTasks <= 0) return null;
  log.journal.mood = inferMood(log.summary);
  log.journal.autoGenerated = generateDailyJournal(log);
  await putDailyLog(log);
  return log;
}

export async function sealTodayJournal(): Promise<DailyLog | null> {
  const today = new Date().toISOString().slice(0, 10);
  return sealDailyJournal(today);
}

export async function compressOldLogsToMonthlySummary(): Promise<void> {
  const logs = await listDailyLogs();
  const now = Date.now();
  const cutoffMs = now - 90 * 24 * 3600 * 1000;
  for (const log of logs) {
    const t = new Date(`${log.date}T00:00:00`).getTime();
    if (t >= cutoffMs) continue;
    const month = monthOf(log.date);
    const prev = (await getMonthlySummary(month)) ?? {
      month,
      totalTasks: 0,
      totalXP: 0,
      totalCrystals: 0,
      days: 0
    };
    prev.totalTasks += log.summary.totalTasks;
    prev.totalXP += log.summary.totalXP;
    prev.totalCrystals += log.summary.totalCrystals;
    prev.days += 1;
    await putMonthlySummary(prev);
    await deleteDailyLog(log.date);
  }
}

export function scheduleDailySeal(onGenerated?: (log: DailyLog) => void): () => void {
  let timer: number | null = null;
  const arm = () => {
    const now = new Date();
    const next = new Date(now);
    next.setHours(23, 59, 0, 0);
    if (next.getTime() <= now.getTime()) {
      next.setDate(next.getDate() + 1);
      next.setHours(23, 59, 0, 0);
    }
    const delay = Math.max(1000, next.getTime() - now.getTime());
    timer = window.setTimeout(async () => {
      const log = await sealTodayJournal();
      if (log && onGenerated) onGenerated(log);
      await compressOldLogsToMonthlySummary();
      arm();
    }, delay);
  };
  arm();
  return () => {
    if (timer) {
      window.clearTimeout(timer);
      timer = null;
    }
  };
}

export function difficultyColor(difficulty: AdventureRecord["difficulty"]): string {
  if (difficulty === "easy") return "bg-emerald-500";
  if (difficulty === "medium") return "bg-amber-500";
  return "bg-rose-500";
}

export function heatValue(log: DailyLog): number {
  return Math.max(log.summary.totalTasks, Math.round(log.summary.totalXP / 35));
}

const MANUAL_MILESTONE_KEY = "life-rpg-manual-milestones";

export function listManualMilestones(): MilestoneItem[] {
  try {
    const raw = localStorage.getItem(MANUAL_MILESTONE_KEY);
    const data = raw ? (JSON.parse(raw) as MilestoneItem[]) : [];
    return data.sort((a, b) => (a.date > b.date ? -1 : 1));
  } catch {
    return [];
  }
}

export function addManualMilestone(input: { date: string; title: string }): void {
  const next: MilestoneItem = {
    id: `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`,
    date: input.date,
    title: input.title,
    kind: "manual"
  };
  const all = listManualMilestones();
  all.unshift(next);
  localStorage.setItem(MANUAL_MILESTONE_KEY, JSON.stringify(all.slice(0, 120)));
}

export function buildMilestones(logs: DailyLog[]): MilestoneItem[] {
  const out: MilestoneItem[] = [];
  let hardDone = false;
  let epicDone = false;
  for (const log of logs) {
    if (log.snapshot.level === 1 || log.snapshot.level === 5 || log.snapshot.level === 10) {
      out.push({
        id: `lv-${log.date}-${log.snapshot.level}`,
        date: log.date,
        title: `Lv.${log.snapshot.level} 达成`,
        kind: "system"
      });
    }
    if (!hardDone && log.adventures.some((a) => a.difficulty === "hard" && a.result === "victory")) {
      hardDone = true;
      out.push({
        id: `hard-first-${log.date}`,
        date: log.date,
        title: "首次完成困难任务",
        kind: "system"
      });
    }
    const badgeStreak = log.checkIns.length >= 3;
    if (badgeStreak) {
      out.push({
        id: `streak7-${log.date}`,
        date: log.date,
        title: "连续打卡里程碑（日志高光日）",
        kind: "system"
      });
    }
    if (!epicDone && log.summary.equipmentAcquired.some((i) => i.rarity === "epic")) {
      epicDone = true;
      out.push({
        id: `epic-${log.date}`,
        date: log.date,
        title: "获得首件史诗装备",
        kind: "system"
      });
    }
  }
  return [...out, ...listManualMilestones()].sort((a, b) => (a.date > b.date ? -1 : 1));
}

export function buildWeeklyBookPages(logs: DailyLog[]): Array<{
  key: string;
  weekLabel: string;
  levelSeries: Array<{ date: string; level: number }>;
  summary: string;
  images: string[];
}> {
  const buckets = new Map<string, DailyLog[]>();
  for (const log of logs) {
    const dt = new Date(`${log.date}T00:00:00`);
    const day = dt.getDay();
    const offset = day === 0 ? -6 : 1 - day;
    const monday = new Date(dt);
    monday.setDate(dt.getDate() + offset);
    const key = monday.toISOString().slice(0, 10);
    const arr = buckets.get(key) ?? [];
    arr.push(log);
    buckets.set(key, arr);
  }
  const pages = Array.from(buckets.entries())
    .sort((a, b) => (a[0] > b[0] ? -1 : 1))
    .map(([k, arr], idx, all) => {
      const sorted = [...arr].sort((a, b) => (a.date > b.date ? 1 : -1));
      const totalTasks = sorted.reduce((s, x) => s + x.summary.totalTasks, 0);
      const topMonster = sorted
        .flatMap((x) => x.adventures)
        .sort((a, b) => b.rewards.xp - a.rewards.xp)[0]?.monsterName;
      const topSkill = sorted.flatMap((x) => x.summary.newSkillsUnlocked)[0];
      const prevTasks =
        idx + 1 < all.length
          ? all[idx + 1][1].reduce((s, x) => s + x.summary.totalTasks, 0)
          : totalTasks;
      const delta = totalTasks - prevTasks;
      const images = sorted
        .flatMap((x) => x.checkIns.filter((c) => c.type === "image").map((c) => c.content))
        .slice(0, 3);
      return {
        key: k,
        weekLabel: `${k} 当周`,
        levelSeries: sorted.map((x) => ({ date: x.date, level: x.snapshot.level })),
        summary: `本周你击败了${topMonster ?? "未知强敌"}，解锁了${topSkill ?? "暂无新技能"}，比上周${
          delta >= 0 ? "多" : "少"
        }完成了${Math.abs(delta)}个任务。`,
        images
      };
    });
  return pages;
}

function avgTaskTime(log: DailyLog): number {
  if (!log.adventures.length) return 0;
  return log.adventures.reduce((s, a) => s + a.duration, 0) / log.adventures.length;
}

function professionShare(log: DailyLog): Record<string, number> {
  const count: Record<string, number> = {};
  for (const a of log.adventures) count[a.profession] = (count[a.profession] ?? 0) + 1;
  const total = Math.max(1, log.adventures.length);
  for (const k of Object.keys(count)) count[k] /= total;
  return count;
}

export function detectNewHabitPatterns(day1: DailyLog, day2: DailyLog): string[] {
  const habits: string[] = [];
  const t1 = avgTaskTime(day1);
  const t2 = avgTaskTime(day2);
  if (t1 > 0 && t2 > 0 && t2 / t1 <= 0.8) habits.push("任务节奏更稳定（平均耗时下降）");
  if (day1.checkIns.length === 0 && day2.checkIns.length > 0) habits.push("形成了复盘打卡习惯");
  if (day2.adventures.filter((a) => a.difficulty === "hard" && a.result === "victory").length >= 2) {
    habits.push("开始持续挑战困难任务");
  }
  const p1 = professionShare(day1);
  const p2 = professionShare(day2);
  for (const k of Object.keys(p2)) {
    if ((p2[k] ?? 0) - (p1[k] ?? 0) >= 0.25) {
      habits.push(`职业专注度提升：${k}`);
      break;
    }
  }
  if (habits.length === 0) habits.push("保持稳定推进");
  return habits;
}

export function compareSnapshots(day1: DailyLog, day2: DailyLog): SnapshotCompareResult {
  const t1 = avgTaskTime(day1);
  const t2 = avgTaskTime(day2);
  return {
    levelDiff: day2.snapshot.level - day1.snapshot.level,
    xpGrowth: day2.summary.totalXP - day1.summary.totalXP,
    statGrowth: {
      str: day2.snapshot.stats.str - day1.snapshot.stats.str,
      int: day2.snapshot.stats.int - day1.snapshot.stats.int,
      agi: day2.snapshot.stats.agi - day1.snapshot.stats.agi,
      cha: day2.snapshot.stats.cha - day1.snapshot.stats.cha,
      con: day2.snapshot.stats.con - day1.snapshot.stats.con
    },
    taskEfficiency: t1 > 0 && t2 > 0 ? t2 / t1 : 1,
    newHabitsFormed: detectNewHabitPatterns(day1, day2)
  };
}

export function compareSnapshotsByDate(logs: DailyLog[], day1: string, day2: string): SnapshotCompareResult | null {
  const a = logs.find((x) => x.date === day1);
  const b = logs.find((x) => x.date === day2);
  if (!a || !b) return null;
  return compareSnapshots(a, b);
}
